#pragma once
// Generated by fontgen.py
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif
extern const lv_font_t font_pl_14;
extern const lv_font_t font_pl_18;
extern const lv_font_t font_pl_24;
extern const lv_font_t font_pl_32;
extern const lv_font_t font_num_48;
#ifdef __cplusplus
}
#endif

// Icons (Font Awesome 5, present in font_pl_*)
#define ICON_SUN          "\xEF\x86\x85"   /* U+F185 */
#define ICON_SOLAR        "\xEF\x96\xBA"   /* U+F5BA */
#define ICON_HOUSE        "\xEF\x80\x95"   /* U+F015 */
#define ICON_PLUG         "\xEF\x87\xA6"   /* U+F1E6 */
#define ICON_TOWER        "\xEF\x94\x99"   /* U+F519 */
#define ICON_INDUSTRY     "\xEF\x89\xB5"   /* U+F275 */
#define ICON_THERMO       "\xEF\x8B\x89"   /* U+F2C9 */
#define ICON_WALLET       "\xEF\x95\x95"   /* U+F555 */
#define ICON_COINS        "\xEF\x94\x9E"   /* U+F51E */
#define ICON_CHART        "\xEF\x88\x81"   /* U+F201 */
#define ICON_PIGGY        "\xEF\x93\x93"   /* U+F4D3 */
#define ICON_MONEY        "\xEF\x94\xBA"   /* U+F53A */
#define ICON_ARROW_UP     "\xEF\x81\xA2"   /* U+F062 */
#define ICON_ARROW_DOWN   "\xEF\x81\xA3"   /* U+F063 */
#define ICON_ARROW_LEFT   "\xEF\x81\xA0"   /* U+F060 */
#define ICON_ARROW_RIGHT  "\xEF\x81\xA1"   /* U+F061 */
#define ICON_LEAF         "\xEF\x81\xAC"   /* U+F06C */
#define ICON_CLOCK        "\xEF\x80\x97"   /* U+F017 */
#define ICON_CALENDAR     "\xEF\x84\xB3"   /* U+F133 */
#define ICON_SEARCH       "\xEF\x80\x82"   /* U+F002 */
#define ICON_INFO         "\xEF\x81\x9A"   /* U+F05A */
#define ICON_CAR          "\xEF\x86\xB9"   /* U+F1B9 */
#define ICON_GAUGE        "\xEF\x8F\xBD"   /* U+F3FD */
#define ICON_MICROCHIP    "\xEF\x8B\x9B"   /* U+F2DB */
#define ICON_BATT_FULL    "\xEF\x89\x80"   /* U+F240 */
#define ICON_BATT_3       "\xEF\x89\x81"   /* U+F241 */
#define ICON_BATT_2       "\xEF\x89\x82"   /* U+F242 */
#define ICON_BATT_1       "\xEF\x89\x83"   /* U+F243 */
#define ICON_BATT_EMPTY   "\xEF\x89\x84"   /* U+F244 */
#define ICON_BOLT         "\xEF\x83\xA7"   /* U+F0E7 */
#define ICON_WIFI         "\xEF\x87\xAB"   /* U+F1EB */
#define ICON_COG          "\xEF\x80\x93"   /* U+F013 */
#define ICON_WARNING      "\xEF\x81\xB1"   /* U+F071 */
#define ICON_CHECK        "\xEF\x80\x8C"   /* U+F00C */
#define ICON_TIMES        "\xEF\x80\x8D"   /* U+F00D */
#define ICON_SYNC         "\xEF\x80\xA1"   /* U+F021 */
#define ICON_LIST         "\xEF\x80\x8B"   /* U+F00B */
#define ICON_HOME_LV      "\xEF\x80\x95"   /* U+F015 */
